### ISSUE TITLE
Cant create custom crafting table with custom size

### ISSUE THREAD

**Issue by UnicornMaster-dev** [val-int1/bigger_craft#3]
Im attempting to use the api to create a 100x100 crafting table ive made the texture
![extreme_crafting_gui](https://github.com/user-attachments/assets/b78a5be6-f5f2-448b-9316-1513285465d1)
ive also made all the required blockstates and models

But the gui wont open am i missing something?

**Comment by val-int1** [comment]
Could you show me your code and the logs? Without those I can't help you (also sorry for the delay in the response).

**Comment by UnicornMaster-dev** [comment]
Thank you for replying. The GUI does open, but it takes a **very** long time. When it finally opens, the image is very zoomed in, which may be due to its resolution of 4280 x 4040. Additionally, the slots are misaligned.
